### ISSUE TITLE
wasm version

### ISSUE THREAD

**Issue by abeq** [jwmcglynn/pixelmatch-cpp17#41]
Do you have plan to release wasm version?
I want to try to use it, if it will be released.

**Comment by jwmcglynn** [comment]
I don't have any specific plans to release a wasm version, however this library should be usable if you're integrating into a larger wasm-based C++ application.

If you'd like to use this library on the web, I'd recommend using the base pixelmatch library from https://github.com/mapbox/pixelmatch. Javascript VMs are quite fast, and the algorithm is the same as pixelmatch-cpp17, so I think both should have about the same performance.
